Jordaan_Vintageandcharity/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import handler404


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('items/', include('items.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profiles/', include('profiles.urls')),
    path('blog/', include('blog.urls')),
    path('reviews/', include('reviews.urls')),
    path('donations/', include('donations.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


handler404 = 'Jordaan_Vintageandcharity.views.handler404'

bag/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<bag_item_id>/', views.add_to_bag, name='add_to_bag'),
    path(
        'remove/<bag_item_id>/', views.remove_from_bag, name='remove_from_bag'
        ),

]

blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views

urlpatterns = [
    path(
        'blog/',
        views.BlogPostList.as_view(),
        name='blog'
    ),
    path(
        '<int:id>/',
        views.BlogPostDetailView.as_view(),
        name='blog_detail'
    ),
    path(
        'create/',
        views.BlogPostCreateView.as_view(),
        name='create_blog'
    ),
    path(
        'edit/<int:id>/',
        views.EditBlogPostView.as_view(),
        name='edit_blog'
    ),
    path(
        'delete/<int:id>/',
        views.BlogPostDelete.as_view(),
        name='blog_delete'
    ),
]

blog/models.py
from django.db import models


class BlogPost(models.Model):
    """ A model to create a blog post """
    charity_name = models.CharField(max_length=200)
    event_name = models.CharField(max_length=200)
    donation_amount = models.DecimalField(max_digits=6, decimal_places=2)
    image = models.ImageField(null=True, blank=True, default='placeholder')
    summary = models.TextField(blank=True)
    charity_location = models.CharField(max_length=200, unique=False)
    charity_website = models.URLField(
        max_length=200, blank=True)
    created_on = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_on']

    def __str__(self):
        return self.event_name

blog/forms.py
from .models import BlogPost
from django import forms


class BlogPostForm(forms.ModelForm):
    """ A form to create a blog post """
    class Meta:
        model = BlogPost
        fields = (
            'event_name',
            'charity_name',
            'image',
            'donation_amount',
            'charity_website',
            'summary',
        )

blog/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import (
    ListView, DetailView, CreateView, UpdateView, DeleteView)
from django.contrib.auth.mixins import UserPassesTestMixin
from django.contrib import messages
from .models import BlogPost
from .forms import BlogPostForm


class BlogPostList(ListView):
    """ A view to return a list of blog posts"""
    model = BlogPost
    queryset = BlogPost.objects.order_by('created_on')
    template_name = 'blog/blog.html'
    paginate_by = 6


class BlogPostDetailView(DetailView):
    """ A view to see the blog post details"""
    model = BlogPost
    template_name = 'blog/blog_detail.html'
    queryset = BlogPost.objects.all()

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(BlogPost, id=id_)


class BlogPostCreateView(UserPassesTestMixin, CreateView):
    """ A view to create a blog post """

    form_class = BlogPostForm
    template_name = 'blog/create_blog.html'
    success_url = "/blog/blog/"
    model = BlogPost

    def test_func(self):
        """tests the user has the correct email for superuser"""
        return self.request.user.is_superuser

    def form_valid(self, form):
        """ If form is valid return to browse blog posts """

        messages.success(self.request, 'Blog post created successfully')
        return super(BlogPostCreateView, self).form_valid(form)


class EditBlogPostView(UserPassesTestMixin, UpdateView):
    """ A view to edit a blog post """

    Model = BlogPost
    form_class = BlogPostForm
    success_url = "/blog/blog/"
    template_name = "blog/edit_blog.html"

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(BlogPost, id=id_)

    def test_func(self):
        """tests the user has the correct email for superuser"""
        return self.request.user.is_superuser

    def form_valid(self, form):
        """ If form is valid return to browse blog posts """
        messages.success(self.request, 'Idea created successfully')
        return super().form_valid(form)


class BlogPostDelete(UserPassesTestMixin, DeleteView):
    """ A view to delete a blog post """
    model = BlogPost
    success_url = "/blog/blog/"
    template_name = "blog/blog_delete.html"

    def test_func(self):
        """tests the user has the correct email for superuser"""
        return self.request.user.is_superuser

    def get_object(self):
        id_ = self.kwargs.get("id")
        return get_object_or_404(BlogPost, id=id_)

blog/templates/blog/blog.html
{% extends "base.html" %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
{% endblock %}

{% block page_header %}
    <div class="container header-container">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}
{% block content %}

<div class="overlay"></div>
<div class="container-fluid">
    <div class="row">
        <div class="col text-center blog-header">
            <h1>Blog</h1>
            <span class="text-center"> 
                {% if request.user.is_superuser %}
                <p>
                    <a class="blog-post-link" href="{% url 'create_blog' %}">Create a Blog Post</a>
                </p>
                {% endif %}
            </span>
        </div>
    </div>
    
    <div class="row">

        <!-- blog post Column -->
        <div class="col-12 mt-3 left">
            <div class="row">
                {% for blogpost in blogpost_list %}
                    <div class="col-md-4">
                        <div class="card mb-4">
                            <div class="card-body">
                                {% if "placeholder" in blogpost.image.url %}
                                <!-- Placeholder image-->
                                <a href="{% url 'blog_detail' blogpost.id %}" class="blog-link">
                                <img class="card-img-top blog-post-page-pic" 
                                src="{{MEDIA_URL}}blog-pic.png" alt="{{ blogpost.charity.name }}">
                                </a>
                                {% else %}
                                <!-- User image -->
                                <a href="{% url 'blog_detail' blogpost.id %}" class="blog-link">
                                <img class="card-img-top blog-post-page-pic" src="{{ blogpost.image.url }}" alt="image related to {{blogpost.event_name}}">
                                </a>
                                {% endif %}
                                <!-- Charity event name and link to  detail page -->
                                <a href="{% url 'blog_detail' blogpost.id %}" class="blog-link">
                                <p class="card-title blog-name-link"><strong>{{ blogpost.event_name }}</strong></p>
                            </a>
                            <hr>
                            <!-- date blog post was updated -->
                            <p class="card-text h6">{{ blogpost.created_on}}</p>

                                
                            </div>
                        </div>
                    </div>
                <!-- starts a new row after every 3 blogs posted -->
                {% if forloop.counter|divisibleby:3 %}

            </div>
            <div class="row">
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- puts next page button at the bottom of the page when there are more than 6 blog posts on a page-->
    {% if is_paginated %}
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-center">
            {% if page_obj.has_previous %}
            <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
            {% endif %}
            {% if page_obj.has_next %}
            <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>

            {% endif %}
        </ul>
    </nav>
    {% endif %}
</div>


{% endblock %}

blog/templates/blog/blog_delete.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
{% endblock %}

{% block page_header %}
    <div class="container header-container-delete-blog">
        <div class="row">
            <div class="col"></div>
        </div>
    </div>
{% endblock %}

<div class="overlay"></div>

<div class="row col-md-8 offset-md-2">
    <div class="col-md-8 offset-md-2 p-3">
        <!-- Delete blog post heading -->
        <h1 class="text-center margin-header">Delete Blog Post</h1>
        <div class="d-flex justify-content-center pt-3">
            <!-- Delete blog post confirmation form-->
            <form method="post" class="text-center p-5">
                {% csrf_token %}
                <p>Are you sure you want to delete "{{ blogpost.event_name }}"?</p>
                <input type="submit" value="Confirm" class="button btn-black">
            </form>
        </div>
    </div>
</div>

{% endblock %}

blog/templates/blog/blog_detail.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
{% endblock %}
<!-- header container for spacing -->
{% block page_header %}
<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>
{% endblock %}
{% block content %}


<div class="masthead">
    <div class="container pic-padding card">
        <div class="row g-0">
            <div class="col-12 text-center blog-header">
                <h1 class="post-title"> {{ blogpost.event_name }}</h1>
                <h2 class="post-title">We raised <strong>£{{ blogpost.donation_amount }}</strong> for {{ blogpost.charity_name }}</h2>
                <!-- Buttons for superuser to delete and edit post -->
                {% if request.user.is_superuser %}
                <p>
                    <a class="blog-post-link" href="{% url 'edit_blog' blogpost.id %}" class="edit-blog" aria-label="Click to edit idea">
                        Edit your blog
                    </a>
                
                    <a class="blog-post-link delete-blog" href="{% url 'blog_delete' blogpost.id %}"  aria-label="Click to delete idea">
                        Delete your blog
                    </a>
                </p>
                {% endif %}
            </div>
        </div>
        <div class="row g-0">
            <div class="d-md-block col-md-12 card">
                {% if "placeholder" in blogpost.picture.url %}
                <!-- placeholder picture -->
                <img class="card-img-top border border-light blog-detail-pic" src="{{MEDIA_URL}}blog-pic.png" alt="">
                {% else %}
                <!-- uploaded picture -->
                <img class="card-img-top border border-light blog-detail-pic" src="{{ blogpost.image.url }}" alt="">
                {% endif %}
            </div>
        </div>
    </div>
    <div class="container summary">
        <div class="row">
            <div class="col card mb4 mt3 left top">
                <!-- Blog Summary -->
                <p class="card-text">
                    {{ blogpost.summary | safe }}
                </p>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="row">
            <div class="card website col-md-12">
                <!-- Charity Website Address-->
                <p> Charity Website:
                    <a class="text-black" href="{{ blogpost.charity_website }}" target="_blank" rel="noopener"
                        aria-label="Please visit the website linked to {{blogpost.charity_name}} (opens in a new window)">
                        {{ blogpost.charity_website }}</a>
                </p>
            </div>
        </div>
    </div>
</div>

{% endblock content %}

blog/templates/blog/create_blog.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
{% endblock %}

<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>


<div class="overlay"></div>
<div class="container blog-header">
    <!-- Create form header and information -->
    <h1>Add a Blog Post</h1>
    <!-- Create blog post form -->
    <form class="create_blog_post_form" method="POST" enctype="multipart/form-data">
        
        {% csrf_token %}

        {{form | crispy}}
    

        <button class="button btn-black btn-lg" type="submit">Submit</button>






    </form>
</div>
{% endblock %}

blog/templates/blog/edit_blog.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
{% load static %}

{% block extra_css %}
    <link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
{% endblock %}

<div class="container header-container">
    <div class="row">
        <div class="col"></div>
    </div>
</div>


<div class="overlay"></div>


<div class="container">
    <!-- Edit blog post form heading and information -->
    <h1 class="text-center blog-header">Edit your Blog Post</h1>
    
    <p>If you have any updates to your blog post please update them here.</p>
    <!-- Edit blog post form-->
    <form class="edit_idea_form" action="{% url 'edit_blog' blogpost.id %}" method="POST" enctype="multipart/form-data">

        {% csrf_token %}

        {{ form.id }}
        {{ form|crispy }}
        {{ form.media }}

        <input class="button btn-black" type="submit" value="Submit">
    </form>

</div>
{% endblock %}